index:
    uri: /
    controller: Controller\HomeController
    httpMethod: [GET]

encrypt:
    uri: /encrypt
    controller: Controller\EncryptController
    httpMethod: [GET,POST]

decrypt:
    uri: /decrypt
    controller: Controller\DecryptController
    httpMethod: [GET,POST]
